#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
五子棋游戏常量定义
"""

SERVER_URL = "http://localhost:5001"
SERVER_PORT = 5001

CHALLENGE_EXPIRE_SECONDS = 60
UNDO_REQUEST_EXPIRE_SECONDS = 30
MOVE_TIMEOUT_SECONDS = 120
PLAYER_OFFLINE_TIMEOUT = 60

BOARD_SIZE = 15

PLAYER_BLACK = 1
PLAYER_WHITE = 2

GAME_PHASE_WAITING = "waiting"
GAME_PHASE_COIN_TOSS = "coin_toss"
GAME_PHASE_PLAYING = "playing"
GAME_PHASE_FINISHED = "finished"

PLAYER_STATUS_IDLE = 'idle'
PLAYER_STATUS_WAITING = 'waiting'
PLAYER_STATUS_CHALLENGING = 'challenging'
PLAYER_STATUS_IN_GAME = 'in_game'

ROOM_STATUS_WAITING = 'waiting'
ROOM_STATUS_COIN_TOSS = 'coin_toss'
ROOM_STATUS_PLAYING = 'playing'
ROOM_STATUS_FINISHED = 'finished'

CHALLENGE_STATUS_PENDING = 'pending'
CHALLENGE_STATUS_ACCEPTED = 'accepted'
CHALLENGE_STATUS_DECLINED = 'declined'
CHALLENGE_STATUS_EXPIRED = 'expired'

UNDO_REQUEST_STATUS_PENDING = 'pending'
UNDO_REQUEST_STATUS_ACCEPTED = 'accepted'
UNDO_REQUEST_STATUS_DECLINED = 'declined'
UNDO_REQUEST_STATUS_EXPIRED = 'expired'

RESIGN_REASON_USER = 'user'
RESIGN_REASON_TIMEOUT = 'timeout'
RESIGN_REASON_OFFLINE = 'offline'

COIN_HEAD = 0
COIN_TAIL = 1

HEARTBEAT_INTERVAL = 30
POLLING_INTERVAL = 2

CHAT_MESSAGE_TYPE_TEXT = 'text'
CHAT_MESSAGE_TYPE_SYSTEM = 'system'
CHAT_MESSAGE_TYPE_MOVE = 'move'
CHAT_MESSAGE_TYPE_UNDO = 'undo'
CHAT_MESSAGE_TYPE_RESIGN = 'resign'
CHAT_MESSAGE_TYPE_DRAW = 'draw'

CHAT_MAX_HISTORY = 100

VERSION = "1.0.0"

ROOM_VISIBILITY_PUBLIC = 'public'
ROOM_VISIBILITY_PRIVATE = 'private'

HOT_GAME_SPECTATOR_THRESHOLD = 1

PLAYER_STATUS_SPECTATING = 'spectating'

CHAT_MESSAGE_TYPE_SPECTATOR_JOIN = 'spectator_join'
CHAT_MESSAGE_TYPE_SPECTATOR_LEAVE = 'spectator_leave'

# 战绩和积分系统
RANK_NEWBIE = '新手'
RANK_IRON = '黑铁'
RANK_BRONZE = '青铜'
RANK_SILVER = '白银'
RANK_GOLD = '黄金'
RANK_PLATINUM = '铂金'
RANK_DIAMOND = '钻石'
RANK_MASTER = '星耀'
RANK_KING = '王者'

RANK_LIST = [
    RANK_NEWBIE,
    RANK_IRON,
    RANK_BRONZE,
    RANK_SILVER,
    RANK_GOLD,
    RANK_PLATINUM,
    RANK_DIAMOND,
    RANK_MASTER,
    RANK_KING
]

# 各段位的积分阈值（达到该积分升级）
RANK_THRESHOLDS = {
    RANK_NEWBIE: 0,
    RANK_IRON: 1,
    RANK_BRONZE: 5,
    RANK_SILVER: 10,
    RANK_GOLD: 20,
    RANK_PLATINUM: 35,
    RANK_DIAMOND: 55,
    RANK_MASTER: 80,
    RANK_KING: 110
}

# 积分变动规则
SCORE_WIN = 1     # 胜一局+1
SCORE_LOSE = -1   # 负一局-1
SCORE_DRAW = 0    # 平局不变