#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
五子棋游戏常量定义
"""

SERVER_URL = "http://localhost:5001"
SERVER_PORT = 5001

CHALLENGE_EXPIRE_SECONDS = 60
UNDO_REQUEST_EXPIRE_SECONDS = 30
MOVE_TIMEOUT_SECONDS = 120
PLAYER_OFFLINE_TIMEOUT = 60

BOARD_SIZE = 15

PLAYER_BLACK = 1
PLAYER_WHITE = 2

GAME_PHASE_WAITING = "waiting"
GAME_PHASE_COIN_TOSS = "coin_toss"
GAME_PHASE_PLAYING = "playing"
GAME_PHASE_FINISHED = "finished"

PLAYER_STATUS_IDLE = 'idle'
PLAYER_STATUS_WAITING = 'waiting'
PLAYER_STATUS_CHALLENGING = 'challenging'
PLAYER_STATUS_IN_GAME = 'in_game'

ROOM_STATUS_WAITING = 'waiting'
ROOM_STATUS_COIN_TOSS = 'coin_toss'
ROOM_STATUS_PLAYING = 'playing'
ROOM_STATUS_FINISHED = 'finished'

CHALLENGE_STATUS_PENDING = 'pending'
CHALLENGE_STATUS_ACCEPTED = 'accepted'
CHALLENGE_STATUS_DECLINED = 'declined'
CHALLENGE_STATUS_EXPIRED = 'expired'

UNDO_REQUEST_STATUS_PENDING = 'pending'
UNDO_REQUEST_STATUS_ACCEPTED = 'accepted'
UNDO_REQUEST_STATUS_DECLINED = 'declined'
UNDO_REQUEST_STATUS_EXPIRED = 'expired'

RESIGN_REASON_USER = 'user'
RESIGN_REASON_TIMEOUT = 'timeout'
RESIGN_REASON_OFFLINE = 'offline'

COIN_HEAD = 0
COIN_TAIL = 1

HEARTBEAT_INTERVAL = 30
POLLING_INTERVAL = 2

CHAT_MESSAGE_TYPE_TEXT = 'text'
CHAT_MESSAGE_TYPE_SYSTEM = 'system'
CHAT_MESSAGE_TYPE_MOVE = 'move'
CHAT_MESSAGE_TYPE_UNDO = 'undo'
CHAT_MESSAGE_TYPE_RESIGN = 'resign'
CHAT_MESSAGE_TYPE_DRAW = 'draw'

CHAT_MAX_HISTORY = 100

VERSION = "1.0.0"
